site_name: Zilverveld Documentatie
site_url: https://docs.zilverveld.nl/
site_description: 'Documentatie van Zilverveld'
site_author: 'Zilverveld'

# Copyright
copyright: Copyright &copy; 2024 Zilverveld

# Repository
repo_url: https://github.com/MythicalLapis0181/zv-documentatie
repo_name: MythicalLapis0181/zv-documentatie
theme:
  name: material
  custom_dir: docs/overrides
  language: nl
  icon:
    logo: material/bank
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Licht
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Donker
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - APV: APV.md
  - Wetboek: wetboek.md
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg