site_name: Zilverveld Documentatie
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Licht
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Donker